sudo: required

language: php

php:
  - 7.0
  - 7.1
  - 7.2

install:
  - composer install

notifications:
  email:
    recipients:
      - alk03073135@gmail.com
    on_success: always
    on_failure: always

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash) -t 0e1e0f1c-26e5-4ef4-b9c1-848b392e7e13